### ISSUE TITLE
Mismatch between Relaton-data-* format and official RNG Schema

### ISSUE THREAD

**Issue by stefanomunarini** [relaton/relaton-py#28]
Some of the data of the relaton-data-* datasets does not match the format of the official [RNG Schema](https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc).

For example, this [dataset](https://github.com/ietf-tools/relaton-data-nist/blob/2fdd243ff49f5b8b231889aaf6c5a4b37c032158/data/NBS_BH_1.yaml#L207) includes the fields "city", "state" and "country" under "contact", while the official schema only allows them to be included under "contact" -> "address":

Current format (wrong):
```
- organization:
    name:
    - National Bureau of Standards
    abbreviation: NBS
    contact:
    - city: Gaithersburg
      state: MD
      country: US
```

Correct format should be:
```
- organization:
    name:
    - National Bureau of Standards
    abbreviation: NBS
    contact:
    - address:
       city: Gaithersburg
       state: MD
       country: US
```

Other datasets with the same issue are: 
1. https://github.com/ietf-tools/relaton-data-3gpp/blob/ccf5604c14c5c925b9c8cbd5bafa9fc0dd71f8f0/data/TR_00.01U_UMTS_3.0.0.yaml#L26  
2. https://github.com/ietf-tools/relaton-data-ieee/blob/dbf20d676030988d58149d6150f29539f4633e97/data/AIEE_11-1937.yaml#L36

**Comment by ronaldtse** [comment]
@andrew2net can you help clarify here? The RNG scheme here does describe an element called "address":
https://github.com/relaton/relaton-models/blob/fee9ea8205756163a1d96de47f9b105dc701d8a0/grammars/biblio.rnc#L163-L177

**Comment by ronaldtse** [comment]
@andrew2net this issue is urgent, can you please help address this ASAP?

**Comment by andrew2net** [comment]
@ronaldtse address isn't an Array, it's a Hash. Shouldn't it be:
```yaml
- address:
    city: Gaithersburg
    state: MD
    country: US
```
