### ISSUE TITLE
Support new Relaton name model for formatted initials

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-py#39]
As described in https://github.com/relaton/relaton-ietf/issues/99, which is required by the following tasks:
* https://github.com/ietf-tools/bibxml-service/issues/238
* https://github.com/ietf-tools/bibxml-service/issues/264

We need to update the Relaton name model to support the preservation of formatted initials of names issued by the RFC Production Center (RPC).

At the model level it has been updated in:
* https://github.com/relaton/relaton-models/pull/42

This task is to update relaton-py to support:
1. The new `formatted-initials` element
2. The updated `forename` element which contains the `initial`attribute

**Comment by ronaldtse** [comment]
@stefanomunarini the data has been updated. Can you verify that the changes to relaton-py work with the new data files? Thanks.

**Comment by stefanomunarini** [comment]
@ronaldtse Can you please confirm the final agreed format? Is it this? 

```yaml
- person:
  name:
    formatted-initials:
      content: J.P.
    forename:
    - initial: J
      content: Jhon
    - initial: P
    - content: Jhonny
    surname: Lang
    completename: J.P. Lang
```

Thanks

**Comment by ronaldtse** [comment]
@opoudjis and @andrew2net can you confirm that the above structure is the one that will happen? We MUST finish implementing support in relaton-py BEFORE deploying the Relaton data structure change.

@stefanomunarini the particular document to monitor is this one:

https://github.com/ietf-tools/relaton-data-rfcs/blob/e6b1d288d5416497fd268039e28b547dbca0d8f2/data/RFC4872.yaml#L22-L38

```yaml
contributor:
- person:
    name:
      surname:
        content: Lang
        language:
        - en
        script:
        - Latn
      completename:
        content: J.P. Lang
        language:
        - en
        script:
        - Latn
  role:
  - editor
```

**Comment by stefanomunarini** [comment]
> @opoudjis and @andrew2net can you confirm that the above structure is the one that will happen? We MUST finish implementing support in relaton-py BEFORE deploying the Relaton data structure change.
> 
> @stefanomunarini the particular document to monitor is this one:
> 
> https://github.com/ietf-tools/relaton-data-rfcs/blob/e6b1d288d5416497fd268039e28b547dbca0d8f2/data/RFC4872.yaml#L22-L38
> 
> ```yaml
> contributor:
> - person:
>     name:
>       surname:
>         content: Lang
>         language:
>         - en
>         script:
>         - Latn
>       completename:
>         content: J.P. Lang
>         language:
>         - en
>         script:
>         - Latn
>   role:
>   - editor
> ```

@ronaldtse I am very confused as I do not see any change compared to the currently implemented format?

**Comment by andrew2net** [comment]
@ronaldtse I confirm we use following structure:
```yaml
- person:
  name:
    given:
      formatted_initials:
        content: J.P.
        language:
        - en
        script:
        - Latn
      forename:
      - initial: J
        content: Jhon
      - initial: P
    surname: Lang
    completename: J.P. Lang
```
