### ISSUE TITLE
place datatype is stale

### ISSUE THREAD

**Issue by kesara** [relaton/relaton-py#66]
`place` is defined as `Optional[str]` [^1].

But the latest relaton model has multiple attributes for `place`.
Example:
```
place:
- city: <string>
  region:
  - name: <string>
    iso: <string>
```

[^1]: https://github.com/relaton/relaton-py/blob/main/relaton/models/bibdata.py#L95
